# ------------------- IMPORTS -------------------
from pydantic import BaseModel
from datetime import datetime

# ------------------- CHATBOT CONTINUE OUTPUT -------------------
class ChatBotContinueOutput(BaseModel):
    # The role of the sender of the message, usually "assistant"
    role: str

    # The message text generated by the AI assistant
    message: str

    # The detected intent associated with this message (can be empty)
    intent: str

    # The session ID for the conversation
    session_id: str

    # Timestamp for when this message was generated
    timestamp: datetime
